[screen]
resolution_width = 1920
resolution_height = 1080
scale = 1.0
capture_debug_path = "artifacts/diagnostics-screen.png"

[screen.capture]
mode = "fullscreen"
left = 0.0
top = 0.0
right = 1.0
bottom = 1.0

[screen.capture.regions.center]
left = 0.333333
top = 0.333333
right = 0.666667
bottom = 0.666667

[screen.capture.regions.compass]
left = 0.3125
top = 0.625
right = 0.5
bottom = 0.9375
